### ISSUE TITLE
Generic name space everywhere or nowhere

### ISSUE THREAD

**Issue by apare** [coveo/vapor#136]
I'm not sure if we should remove all namespace or add them everywhere

For example we have `coveo-checkbox` and `coveo-form` but we also have `input-field` `form-group`

I think we should go with Coveo everywhere because this reduce the chance to match a external lib css (Salesforce)

**Comment by JPLachance** [comment]
After a discussion with @wfortin, we will remove the `coveo-` prefix everywhere and bump a major version.
