### ISSUE TITLE
Compilation error on scss\common\common.scss

### ISSUE THREAD

**Issue by louis-bompart** [coveo/vapor#576]
On the PR #551 , `$base-font-family` has been moved from [./scss/common/font.scss](https://github.com/coveo/vapor/blob/master/scss/common/font.scss) to [./scss/variable.scss](https://github.com/coveo/vapor/blob/master/scss/variables.scss).
However, the variable is being used by [./scss/common/common.scss](https://github.com/coveo/vapor/blob/master/scss/common/common.scss#L17).

So [./scss/common/common.scss](https://github.com/coveo/vapor/blob/master/scss/common/common.scss) should either not reference the variable anymore, or import [./scss/variable.scss](https://github.com/coveo/vapor/blob/master/scss/variables.scss).

The latest option seems the most legit one, because imo, that just an oversight that occured during #551 .

**Comment by sroy3** [comment]
[./scss/common/common.scss](https://github.com/coveo/vapor/blob/master/scss/common/common.scss#L17) has also been moved under  [./scss/variable.scss](https://github.com/coveo/vapor/blob/master/scss/variables.scss) in  [./scss/guide.scss](https://github.com/coveo/vapor/blob/master/scss/guide.scss) where everything is imported. Although there is still an import for the font file, it was never required. We do not currently support importing only one file from the styleguide.

**Comment by louis-bompart** [comment]
So, if we want to import the scss into our project, we should import [guide.scss](https://github.com/coveo/vapor/blob/master/scss/guide.scss) ?

**Comment by sroy3** [comment]
You can import `variables.scss` and the other file you want. But you might be missing `palette.scss` or other common files as well. You can also create your own `guide.scss`. At first, vapor wasn't even meant for directly importing scss files, but only the resulting css one. We are currently working on a V2 version that will be more flexible and better suited for importing things granularly.

**Comment by louis-bompart** [comment]
Okay, thanks!
